"""empty message

Revision ID: e0c2b8ce95a9
Revises: 
Create Date: 2019-05-05 11:26:53.592578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c2b8ce95a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('co', sa.Float(precision=4), nullable=True),
    sa.Column('so2', sa.Float(precision=4), nullable=True),
    sa.Column('no2', sa.Float(precision=4), nullable=True),
    sa.Column('pm_1_0', sa.Float(precision=4), nullable=True),
    sa.Column('pm_2_5', sa.Float(precision=4), nullable=True),
    sa.Column('pm_10', sa.Float(precision=4), nullable=True),
    sa.Column('o3', sa.Float(precision=4), nullable=True),
    sa.Column('t', sa.Float(precision=4), nullable=True),
    sa.Column('wd', sa.Integer(), nullable=True),
    sa.Column('ws', sa.Float(precision=4), nullable=True),
    sa.Column('h', sa.Float(precision=4), nullable=True),
    sa.Column('p', sa.Float(precision=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_quality')
    # ### end Alembic commands ###
